language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed minhthanh1703/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user minhthanh1703/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend minhthanh1703/udagram-frontend:local
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy minhthanh1703/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push minhthanh1703/udagram-api-feed:v1
  - docker push minhthanh1703/udagram-api-user:v1
  - docker push minhthanh1703/udagram-frontend:local
  - docker push minhthanh1703/reverseproxy:v1
